name: CI/CD deploy release
on: 
  #push:
    #branches: [ "master"]
  pull_request:
    branches: [ "release"]
jobs:
  ci_cd_deploy_release:
    runs-on: ubuntu-latest

    steps:
      - run: ls -la
      - uses: actions/checkout@v2
      - run: ls -la
      - run: echo 'hello world'
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: install dependencies 
        run: npm ci

      - name: build setup
        run: npm run build

      - name: list dir
        run: ls -la dist/admin-cv/browser

      - name: download, run httpd image
        run:  |
            docker run -d --name serving_base httpd
      - name: docker ps
        run:  |
            docker ps
      - name: cp angular build to container
        run:  |
            docker cp dist/admin-cv/browser/. serving_base:/usr/local/apache2/htdocs
      - name: list container
        run:  |
            docker exec serving_base ls -la /usr/local/apache2/htdocs
      - name: build custom docker image
        run: docker commit --change "ENV MODEL_NAME2  ${{ secrets.MODEL_NAME2}}"
             serving_base ${{ secrets.DOCKER_USER}}/${{secrets.MODEL_NAME2}}:${{github.sha}}

      - name: list images
        run:  |
            docker images
      - name: build login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker push
        run: docker push ${{ secrets.DOCKER_USER}}/${{secrets.MODEL_NAME2}}:${{github.sha}}
